
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point data_in[15] data_in[15] -type PI PI
add mapped point data_in[14] data_in[14] -type PI PI
add mapped point data_in[13] data_in[13] -type PI PI
add mapped point data_in[12] data_in[12] -type PI PI
add mapped point data_in[11] data_in[11] -type PI PI
add mapped point data_in[10] data_in[10] -type PI PI
add mapped point data_in[9] data_in[9] -type PI PI
add mapped point data_in[8] data_in[8] -type PI PI
add mapped point data_in[7] data_in[7] -type PI PI
add mapped point data_in[6] data_in[6] -type PI PI
add mapped point data_in[5] data_in[5] -type PI PI
add mapped point data_in[4] data_in[4] -type PI PI
add mapped point data_in[3] data_in[3] -type PI PI
add mapped point data_in[2] data_in[2] -type PI PI
add mapped point data_in[1] data_in[1] -type PI PI
add mapped point data_in[0] data_in[0] -type PI PI
add mapped point threshold_in[15] threshold_in[15] -type PI PI
add mapped point threshold_in[14] threshold_in[14] -type PI PI
add mapped point threshold_in[13] threshold_in[13] -type PI PI
add mapped point threshold_in[12] threshold_in[12] -type PI PI
add mapped point threshold_in[11] threshold_in[11] -type PI PI
add mapped point threshold_in[10] threshold_in[10] -type PI PI
add mapped point threshold_in[9] threshold_in[9] -type PI PI
add mapped point threshold_in[8] threshold_in[8] -type PI PI
add mapped point threshold_in[7] threshold_in[7] -type PI PI
add mapped point threshold_in[6] threshold_in[6] -type PI PI
add mapped point threshold_in[5] threshold_in[5] -type PI PI
add mapped point threshold_in[4] threshold_in[4] -type PI PI
add mapped point threshold_in[3] threshold_in[3] -type PI PI
add mapped point threshold_in[2] threshold_in[2] -type PI PI
add mapped point threshold_in[1] threshold_in[1] -type PI PI
add mapped point threshold_in[0] threshold_in[0] -type PI PI
add mapped point class_a_thresh_in[7] class_a_thresh_in[7] -type PI PI
add mapped point class_a_thresh_in[6] class_a_thresh_in[6] -type PI PI
add mapped point class_a_thresh_in[5] class_a_thresh_in[5] -type PI PI
add mapped point class_a_thresh_in[4] class_a_thresh_in[4] -type PI PI
add mapped point class_a_thresh_in[3] class_a_thresh_in[3] -type PI PI
add mapped point class_a_thresh_in[2] class_a_thresh_in[2] -type PI PI
add mapped point class_a_thresh_in[1] class_a_thresh_in[1] -type PI PI
add mapped point class_a_thresh_in[0] class_a_thresh_in[0] -type PI PI
add mapped point class_b_thresh_in[7] class_b_thresh_in[7] -type PI PI
add mapped point class_b_thresh_in[6] class_b_thresh_in[6] -type PI PI
add mapped point class_b_thresh_in[5] class_b_thresh_in[5] -type PI PI
add mapped point class_b_thresh_in[4] class_b_thresh_in[4] -type PI PI
add mapped point class_b_thresh_in[3] class_b_thresh_in[3] -type PI PI
add mapped point class_b_thresh_in[2] class_b_thresh_in[2] -type PI PI
add mapped point class_b_thresh_in[1] class_b_thresh_in[1] -type PI PI
add mapped point class_b_thresh_in[0] class_b_thresh_in[0] -type PI PI
add mapped point timeout_period_in[15] timeout_period_in[15] -type PI PI
add mapped point timeout_period_in[14] timeout_period_in[14] -type PI PI
add mapped point timeout_period_in[13] timeout_period_in[13] -type PI PI
add mapped point timeout_period_in[12] timeout_period_in[12] -type PI PI
add mapped point timeout_period_in[11] timeout_period_in[11] -type PI PI
add mapped point timeout_period_in[10] timeout_period_in[10] -type PI PI
add mapped point timeout_period_in[9] timeout_period_in[9] -type PI PI
add mapped point timeout_period_in[8] timeout_period_in[8] -type PI PI
add mapped point timeout_period_in[7] timeout_period_in[7] -type PI PI
add mapped point timeout_period_in[6] timeout_period_in[6] -type PI PI
add mapped point timeout_period_in[5] timeout_period_in[5] -type PI PI
add mapped point timeout_period_in[4] timeout_period_in[4] -type PI PI
add mapped point timeout_period_in[3] timeout_period_in[3] -type PI PI
add mapped point timeout_period_in[2] timeout_period_in[2] -type PI PI
add mapped point timeout_period_in[1] timeout_period_in[1] -type PI PI
add mapped point timeout_period_in[0] timeout_period_in[0] -type PI PI

//output ports
add mapped point spike_detection spike_detection -type PO PO
add mapped point event_out[1] event_out[1] -type PO PO
add mapped point event_out[0] event_out[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point classifier_instance/event_out[1]/q classifier_instance/event_out_reg[1]/Q -type DFF DFF
add mapped point classifier_instance/event_out[0]/q classifier_instance/event_out_reg[0]/Q -type DFF DFF
add mapped point classifier_instance/class_a_threshold[6]/q classifier_instance/class_a_threshold_reg[6]/Q -type DFF DFF
add mapped point classifier_instance/class_b_threshold[2]/q classifier_instance/class_b_threshold_reg[2]/Q -type DFF DFF
add mapped point classifier_instance/class_b_threshold[1]/q classifier_instance/class_b_threshold_reg[1]/Q -type DFF DFF
add mapped point classifier_instance/class_a_threshold[1]/q classifier_instance/class_a_threshold_reg[1]/Q -type DFF DFF
add mapped point classifier_instance/timeout_period[7]/q classifier_instance/timeout_period_reg[7]/Q -type DFF DFF
add mapped point classifier_instance/class_a_threshold[5]/q classifier_instance/class_a_threshold_reg[5]/Q -type DFF DFF
add mapped point classifier_instance/timeout_period[6]/q classifier_instance/timeout_period_reg[6]/Q -type DFF DFF
add mapped point classifier_instance/timeout_period[5]/q classifier_instance/timeout_period_reg[5]/Q -type DFF DFF
add mapped point classifier_instance/timeout_period[15]/q classifier_instance/timeout_period_reg[15]/Q -type DFF DFF
add mapped point classifier_instance/timeout_period[3]/q classifier_instance/timeout_period_reg[3]/Q -type DFF DFF
add mapped point classifier_instance/class_a_threshold[7]/q classifier_instance/class_a_threshold_reg[7]/Q -type DFF DFF
add mapped point classifier_instance/class_a_threshold[4]/q classifier_instance/class_a_threshold_reg[4]/Q -type DFF DFF
add mapped point classifier_instance/timeout_period[14]/q classifier_instance/timeout_period_reg[14]/Q -type DFF DFF
add mapped point classifier_instance/timeout_period[2]/q classifier_instance/timeout_period_reg[2]/Q -type DFF DFF
add mapped point classifier_instance/timeout_period[1]/q classifier_instance/timeout_period_reg[1]/Q -type DFF DFF
add mapped point classifier_instance/timeout_period[0]/q classifier_instance/timeout_period_reg[0]/Q -type DFF DFF
add mapped point classifier_instance/class_b_threshold[7]/q classifier_instance/class_b_threshold_reg[7]/Q -type DFF DFF
add mapped point classifier_instance/class_a_threshold[3]/q classifier_instance/class_a_threshold_reg[3]/Q -type DFF DFF
add mapped point classifier_instance/timeout_period[12]/q classifier_instance/timeout_period_reg[12]/Q -type DFF DFF
add mapped point classifier_instance/class_b_threshold[6]/q classifier_instance/class_b_threshold_reg[6]/Q -type DFF DFF
add mapped point classifier_instance/class_b_threshold[5]/q classifier_instance/class_b_threshold_reg[5]/Q -type DFF DFF
add mapped point classifier_instance/timeout_period[11]/q classifier_instance/timeout_period_reg[11]/Q -type DFF DFF
add mapped point classifier_instance/class_b_threshold[4]/q classifier_instance/class_b_threshold_reg[4]/Q -type DFF DFF
add mapped point classifier_instance/class_b_threshold[3]/q classifier_instance/class_b_threshold_reg[3]/Q -type DFF DFF
add mapped point classifier_instance/timeout_period[10]/q classifier_instance/timeout_period_reg[10]/Q -type DFF DFF
add mapped point classifier_instance/class_a_threshold[2]/q classifier_instance/class_a_threshold_reg[2]/Q -type DFF DFF
add mapped point classifier_instance/timeout_period[9]/q classifier_instance/timeout_period_reg[9]/Q -type DFF DFF
add mapped point classifier_instance/class_b_threshold[0]/q classifier_instance/class_b_threshold_reg[0]/Q -type DFF DFF
add mapped point classifier_instance/timeout_period[8]/q classifier_instance/timeout_period_reg[8]/Q -type DFF DFF
add mapped point classifier_instance/class_a_threshold[0]/q classifier_instance/class_a_threshold_reg[0]/Q -type DFF DFF
add mapped point classifier_instance/timeout_period[4]/q classifier_instance/timeout_period_reg[4]/Q -type DFF DFF
add mapped point classifier_instance/timeout_period[13]/q classifier_instance/timeout_period_reg[13]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[0]/q classifier_instance/counter_confirmation_a_reg[0]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[1]/q classifier_instance/counter_confirmation_a_reg[1]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[2]/q classifier_instance/counter_confirmation_a_reg[2]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[3]/q classifier_instance/counter_confirmation_a_reg[3]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[4]/q classifier_instance/counter_confirmation_a_reg[4]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[5]/q classifier_instance/counter_confirmation_a_reg[5]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[6]/q classifier_instance/counter_confirmation_a_reg[6]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[7]/q classifier_instance/counter_confirmation_a_reg[7]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[8]/q classifier_instance/counter_confirmation_a_reg[8]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[9]/q classifier_instance/counter_confirmation_a_reg[9]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[10]/q classifier_instance/counter_confirmation_a_reg[10]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[11]/q classifier_instance/counter_confirmation_a_reg[11]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[12]/q classifier_instance/counter_confirmation_a_reg[12]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[13]/q classifier_instance/counter_confirmation_a_reg[13]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[14]/q classifier_instance/counter_confirmation_a_reg[14]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[15]/q classifier_instance/counter_confirmation_a_reg[15]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[16]/q classifier_instance/counter_confirmation_a_reg[16]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[17]/q classifier_instance/counter_confirmation_a_reg[17]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[18]/q classifier_instance/counter_confirmation_a_reg[18]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[19]/q classifier_instance/counter_confirmation_a_reg[19]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[20]/q classifier_instance/counter_confirmation_a_reg[20]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[21]/q classifier_instance/counter_confirmation_a_reg[21]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[22]/q classifier_instance/counter_confirmation_a_reg[22]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[23]/q classifier_instance/counter_confirmation_a_reg[23]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[24]/q classifier_instance/counter_confirmation_a_reg[24]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[25]/q classifier_instance/counter_confirmation_a_reg[25]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[26]/q classifier_instance/counter_confirmation_a_reg[26]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[27]/q classifier_instance/counter_confirmation_a_reg[27]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[28]/q classifier_instance/counter_confirmation_a_reg[28]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[29]/q classifier_instance/counter_confirmation_a_reg[29]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[30]/q classifier_instance/counter_confirmation_a_reg[30]/Q -type DFF DFF
add mapped point classifier_instance/counter_confirmation_a[31]/q classifier_instance/counter_confirmation_a_reg[31]/Q -type DFF DFF
add mapped point classifier_instance/current_event[0]/q classifier_instance/current_event_reg[0]/Q -type DFF DFF
add mapped point classifier_instance/current_event[1]/q classifier_instance/current_event_reg[1]/Q -type DFF DFF
add mapped point classifier_instance/excitability[2]/q classifier_instance/excitability_reg[2]/Q -type DFF DFF
add mapped point classifier_instance/excitability[3]/q classifier_instance/excitability_reg[3]/Q -type DFF DFF
add mapped point classifier_instance/excitability[4]/q classifier_instance/excitability_reg[4]/Q -type DFF DFF
add mapped point classifier_instance/excitability[5]/q classifier_instance/excitability_reg[5]/Q -type DFF DFF
add mapped point classifier_instance/excitability[6]/q classifier_instance/excitability_reg[6]/Q -type DFF DFF
add mapped point classifier_instance/excitability[7]/q classifier_instance/excitability_reg[7]/Q -type DFF DFF
add mapped point classifier_instance/excitability[8]/q classifier_instance/excitability_reg[8]/Q -type DFF DFF
add mapped point classifier_instance/excitability[9]/q classifier_instance/excitability_reg[9]/Q -type DFF DFF
add mapped point classifier_instance/excitability[10]/q classifier_instance/excitability_reg[10]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[0]/q classifier_instance/last_a_section_end_reg[0]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[1]/q classifier_instance/last_a_section_end_reg[1]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[2]/q classifier_instance/last_a_section_end_reg[2]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[3]/q classifier_instance/last_a_section_end_reg[3]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[4]/q classifier_instance/last_a_section_end_reg[4]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[5]/q classifier_instance/last_a_section_end_reg[5]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[6]/q classifier_instance/last_a_section_end_reg[6]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[7]/q classifier_instance/last_a_section_end_reg[7]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[8]/q classifier_instance/last_a_section_end_reg[8]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[9]/q classifier_instance/last_a_section_end_reg[9]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[10]/q classifier_instance/last_a_section_end_reg[10]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[11]/q classifier_instance/last_a_section_end_reg[11]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[12]/q classifier_instance/last_a_section_end_reg[12]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[13]/q classifier_instance/last_a_section_end_reg[13]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[14]/q classifier_instance/last_a_section_end_reg[14]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[15]/q classifier_instance/last_a_section_end_reg[15]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[16]/q classifier_instance/last_a_section_end_reg[16]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[17]/q classifier_instance/last_a_section_end_reg[17]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[18]/q classifier_instance/last_a_section_end_reg[18]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[19]/q classifier_instance/last_a_section_end_reg[19]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[20]/q classifier_instance/last_a_section_end_reg[20]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[21]/q classifier_instance/last_a_section_end_reg[21]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[22]/q classifier_instance/last_a_section_end_reg[22]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[23]/q classifier_instance/last_a_section_end_reg[23]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[24]/q classifier_instance/last_a_section_end_reg[24]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[25]/q classifier_instance/last_a_section_end_reg[25]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[26]/q classifier_instance/last_a_section_end_reg[26]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[27]/q classifier_instance/last_a_section_end_reg[27]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[28]/q classifier_instance/last_a_section_end_reg[28]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[29]/q classifier_instance/last_a_section_end_reg[29]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[30]/q classifier_instance/last_a_section_end_reg[30]/Q -type DFF DFF
add mapped point classifier_instance/last_a_section_end[31]/q classifier_instance/last_a_section_end_reg[31]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[0]/q classifier_instance/last_event_sample_count_reg[0]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[1]/q classifier_instance/last_event_sample_count_reg[1]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[2]/q classifier_instance/last_event_sample_count_reg[2]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[3]/q classifier_instance/last_event_sample_count_reg[3]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[4]/q classifier_instance/last_event_sample_count_reg[4]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[5]/q classifier_instance/last_event_sample_count_reg[5]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[6]/q classifier_instance/last_event_sample_count_reg[6]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[7]/q classifier_instance/last_event_sample_count_reg[7]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[8]/q classifier_instance/last_event_sample_count_reg[8]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[9]/q classifier_instance/last_event_sample_count_reg[9]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[10]/q classifier_instance/last_event_sample_count_reg[10]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[11]/q classifier_instance/last_event_sample_count_reg[11]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[12]/q classifier_instance/last_event_sample_count_reg[12]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[13]/q classifier_instance/last_event_sample_count_reg[13]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[14]/q classifier_instance/last_event_sample_count_reg[14]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[15]/q classifier_instance/last_event_sample_count_reg[15]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[16]/q classifier_instance/last_event_sample_count_reg[16]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[17]/q classifier_instance/last_event_sample_count_reg[17]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[18]/q classifier_instance/last_event_sample_count_reg[18]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[19]/q classifier_instance/last_event_sample_count_reg[19]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[20]/q classifier_instance/last_event_sample_count_reg[20]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[21]/q classifier_instance/last_event_sample_count_reg[21]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[22]/q classifier_instance/last_event_sample_count_reg[22]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[23]/q classifier_instance/last_event_sample_count_reg[23]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[24]/q classifier_instance/last_event_sample_count_reg[24]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[25]/q classifier_instance/last_event_sample_count_reg[25]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[26]/q classifier_instance/last_event_sample_count_reg[26]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[27]/q classifier_instance/last_event_sample_count_reg[27]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[28]/q classifier_instance/last_event_sample_count_reg[28]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[29]/q classifier_instance/last_event_sample_count_reg[29]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[30]/q classifier_instance/last_event_sample_count_reg[30]/Q -type DFF DFF
add mapped point classifier_instance/last_event_sample_count[31]/q classifier_instance/last_event_sample_count_reg[31]/Q -type DFF DFF
add mapped point classifier_instance/previous_event[0]/q classifier_instance/previous_event_reg[0]/Q -type DFF DFF
add mapped point classifier_instance/previous_event[1]/q classifier_instance/previous_event_reg[1]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[0]/q classifier_instance/sample_count_reg[0]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[1]/q classifier_instance/sample_count_reg[1]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[2]/q classifier_instance/sample_count_reg[2]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[3]/q classifier_instance/sample_count_reg[3]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[4]/q classifier_instance/sample_count_reg[4]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[5]/q classifier_instance/sample_count_reg[5]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[6]/q classifier_instance/sample_count_reg[6]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[7]/q classifier_instance/sample_count_reg[7]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[8]/q classifier_instance/sample_count_reg[8]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[9]/q classifier_instance/sample_count_reg[9]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[10]/q classifier_instance/sample_count_reg[10]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[11]/q classifier_instance/sample_count_reg[11]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[12]/q classifier_instance/sample_count_reg[12]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[13]/q classifier_instance/sample_count_reg[13]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[14]/q classifier_instance/sample_count_reg[14]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[15]/q classifier_instance/sample_count_reg[15]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[16]/q classifier_instance/sample_count_reg[16]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[17]/q classifier_instance/sample_count_reg[17]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[18]/q classifier_instance/sample_count_reg[18]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[19]/q classifier_instance/sample_count_reg[19]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[20]/q classifier_instance/sample_count_reg[20]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[21]/q classifier_instance/sample_count_reg[21]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[22]/q classifier_instance/sample_count_reg[22]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[23]/q classifier_instance/sample_count_reg[23]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[24]/q classifier_instance/sample_count_reg[24]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[25]/q classifier_instance/sample_count_reg[25]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[26]/q classifier_instance/sample_count_reg[26]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[27]/q classifier_instance/sample_count_reg[27]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[28]/q classifier_instance/sample_count_reg[28]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[29]/q classifier_instance/sample_count_reg[29]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[30]/q classifier_instance/sample_count_reg[30]/Q -type DFF DFF
add mapped point classifier_instance/sample_count[31]/q classifier_instance/sample_count_reg[31]/Q -type DFF DFF
add mapped point spike_detector_instance/x1[0]/q spike_detector_instance/x1_reg[0]/Q -type DFF DFF
add mapped point spike_detector_instance/x1[14]/q spike_detector_instance/x1_reg[14]/Q -type DFF DFF
add mapped point spike_detector_instance/x1[12]/q spike_detector_instance/x1_reg[12]/Q -type DFF DFF
add mapped point spike_detector_instance/x1[8]/q spike_detector_instance/x1_reg[8]/Q -type DFF DFF
add mapped point spike_detector_instance/x1[15]/q spike_detector_instance/x1_reg[15]/Q -type DFF DFF
add mapped point spike_detector_instance/x1[7]/q spike_detector_instance/x1_reg[7]/Q -type DFF DFF
add mapped point spike_detector_instance/x1[11]/q spike_detector_instance/x1_reg[11]/Q -type DFF DFF
add mapped point spike_detector_instance/x1[6]/q spike_detector_instance/x1_reg[6]/Q -type DFF DFF
add mapped point spike_detector_instance/x1[3]/q spike_detector_instance/x1_reg[3]/Q -type DFF DFF
add mapped point spike_detector_instance/x1[13]/q spike_detector_instance/x1_reg[13]/Q -type DFF DFF
add mapped point spike_detector_instance/x1[10]/q spike_detector_instance/x1_reg[10]/Q -type DFF DFF
add mapped point spike_detector_instance/x1[4]/q spike_detector_instance/x1_reg[4]/Q -type DFF DFF
add mapped point spike_detector_instance/x1[5]/q spike_detector_instance/x1_reg[5]/Q -type DFF DFF
add mapped point spike_detector_instance/x1[9]/q spike_detector_instance/x1_reg[9]/Q -type DFF DFF
add mapped point spike_detector_instance/x1[2]/q spike_detector_instance/x1_reg[2]/Q -type DFF DFF
add mapped point spike_detector_instance/x1[1]/q spike_detector_instance/x1_reg[1]/Q -type DFF DFF
add mapped point spike_detector_instance/x2[3]/q spike_detector_instance/x2_reg[3]/Q -type DFF DFF
add mapped point spike_detector_instance/threshold[14]/q spike_detector_instance/threshold_reg[14]/Q -type DFF DFF
add mapped point spike_detector_instance/threshold[13]/q spike_detector_instance/threshold_reg[13]/Q -type DFF DFF
add mapped point spike_detector_instance/threshold[12]/q spike_detector_instance/threshold_reg[12]/Q -type DFF DFF
add mapped point spike_detector_instance/threshold[11]/q spike_detector_instance/threshold_reg[11]/Q -type DFF DFF
add mapped point spike_detector_instance/threshold[10]/q spike_detector_instance/threshold_reg[10]/Q -type DFF DFF
add mapped point spike_detector_instance/threshold[9]/q spike_detector_instance/threshold_reg[9]/Q -type DFF DFF
add mapped point spike_detector_instance/threshold[3]/q spike_detector_instance/threshold_reg[3]/Q -type DFF DFF
add mapped point spike_detector_instance/threshold[1]/q spike_detector_instance/threshold_reg[1]/Q -type DFF DFF
add mapped point spike_detector_instance/threshold[0]/q spike_detector_instance/threshold_reg[0]/Q -type DFF DFF
add mapped point spike_detector_instance/x2[6]/q spike_detector_instance/x2_reg[6]/Q -type DFF DFF
add mapped point spike_detector_instance/x2[10]/q spike_detector_instance/x2_reg[10]/Q -type DFF DFF
add mapped point spike_detector_instance/x2[0]/q spike_detector_instance/x2_reg[0]/Q -type DFF DFF
add mapped point spike_detector_instance/x2[1]/q spike_detector_instance/x2_reg[1]/Q -type DFF DFF
add mapped point spike_detector_instance/x2[2]/q spike_detector_instance/x2_reg[2]/Q -type DFF DFF
add mapped point spike_detector_instance/threshold[15]/q spike_detector_instance/threshold_reg[15]/Q -type DFF DFF
add mapped point spike_detector_instance/threshold[2]/q spike_detector_instance/threshold_reg[2]/Q -type DFF DFF
add mapped point spike_detector_instance/x2[5]/q spike_detector_instance/x2_reg[5]/Q -type DFF DFF
add mapped point spike_detector_instance/x2[7]/q spike_detector_instance/x2_reg[7]/Q -type DFF DFF
add mapped point spike_detector_instance/x2[8]/q spike_detector_instance/x2_reg[8]/Q -type DFF DFF
add mapped point spike_detector_instance/x2[9]/q spike_detector_instance/x2_reg[9]/Q -type DFF DFF
add mapped point spike_detector_instance/x2[11]/q spike_detector_instance/x2_reg[11]/Q -type DFF DFF
add mapped point spike_detector_instance/x2[12]/q spike_detector_instance/x2_reg[12]/Q -type DFF DFF
add mapped point spike_detector_instance/x2[13]/q spike_detector_instance/x2_reg[13]/Q -type DFF DFF
add mapped point spike_detector_instance/x2[14]/q spike_detector_instance/x2_reg[14]/Q -type DFF DFF
add mapped point spike_detector_instance/x2[15]/q spike_detector_instance/x2_reg[15]/Q -type DFF DFF
add mapped point spike_detector_instance/threshold[8]/q spike_detector_instance/threshold_reg[8]/Q -type DFF DFF
add mapped point spike_detector_instance/threshold[7]/q spike_detector_instance/threshold_reg[7]/Q -type DFF DFF
add mapped point spike_detector_instance/threshold[6]/q spike_detector_instance/threshold_reg[6]/Q -type DFF DFF
add mapped point spike_detector_instance/threshold[5]/q spike_detector_instance/threshold_reg[5]/Q -type DFF DFF
add mapped point spike_detector_instance/threshold[4]/q spike_detector_instance/threshold_reg[4]/Q -type DFF DFF
add mapped point spike_detector_instance/x2[4]/q spike_detector_instance/x2_reg[4]/Q -type DFF DFF
add mapped point spike_detector_instance/x3[9]/q spike_detector_instance/x3_reg[9]/Q -type DFF DFF
add mapped point spike_detector_instance/x3[11]/q spike_detector_instance/x3_reg[11]/Q -type DFF DFF
add mapped point spike_detector_instance/x3[12]/q spike_detector_instance/x3_reg[12]/Q -type DFF DFF
add mapped point spike_detector_instance/x3[13]/q spike_detector_instance/x3_reg[13]/Q -type DFF DFF
add mapped point spike_detector_instance/x3[15]/q spike_detector_instance/x3_reg[15]/Q -type DFF DFF
add mapped point spike_detector_instance/x3[2]/q spike_detector_instance/x3_reg[2]/Q -type DFF DFF
add mapped point spike_detector_instance/x3[10]/q spike_detector_instance/x3_reg[10]/Q -type DFF DFF
add mapped point spike_detector_instance/x3[6]/q spike_detector_instance/x3_reg[6]/Q -type DFF DFF
add mapped point spike_detector_instance/x3[0]/q spike_detector_instance/x3_reg[0]/Q -type DFF DFF
add mapped point spike_detector_instance/x3[1]/q spike_detector_instance/x3_reg[1]/Q -type DFF DFF
add mapped point spike_detector_instance/x3[3]/q spike_detector_instance/x3_reg[3]/Q -type DFF DFF
add mapped point spike_detector_instance/x3[4]/q spike_detector_instance/x3_reg[4]/Q -type DFF DFF
add mapped point spike_detector_instance/x3[5]/q spike_detector_instance/x3_reg[5]/Q -type DFF DFF
add mapped point spike_detector_instance/x3[7]/q spike_detector_instance/x3_reg[7]/Q -type DFF DFF
add mapped point spike_detector_instance/x3[8]/q spike_detector_instance/x3_reg[8]/Q -type DFF DFF
add mapped point spike_detector_instance/x3[14]/q spike_detector_instance/x3_reg[14]/Q -type DFF DFF
add mapped point spike_detector_instance/x4[14]/q spike_detector_instance/x4_reg[14]/Q -type DFF DFF
add mapped point spike_detector_instance/x4[1]/q spike_detector_instance/x4_reg[1]/Q -type DFF DFF
add mapped point spike_detector_instance/x4[15]/q spike_detector_instance/x4_reg[15]/Q -type DFF DFF
add mapped point spike_detector_instance/x4[0]/q spike_detector_instance/x4_reg[0]/Q -type DFF DFF
add mapped point spike_detector_instance/x4[3]/q spike_detector_instance/x4_reg[3]/Q -type DFF DFF
add mapped point spike_detector_instance/x4[4]/q spike_detector_instance/x4_reg[4]/Q -type DFF DFF
add mapped point spike_detector_instance/x4[13]/q spike_detector_instance/x4_reg[13]/Q -type DFF DFF
add mapped point spike_detector_instance/x4[5]/q spike_detector_instance/x4_reg[5]/Q -type DFF DFF
add mapped point spike_detector_instance/x4[8]/q spike_detector_instance/x4_reg[8]/Q -type DFF DFF
add mapped point spike_detector_instance/x4[11]/q spike_detector_instance/x4_reg[11]/Q -type DFF DFF
add mapped point spike_detector_instance/x4[10]/q spike_detector_instance/x4_reg[10]/Q -type DFF DFF
add mapped point spike_detector_instance/x4[6]/q spike_detector_instance/x4_reg[6]/Q -type DFF DFF
add mapped point spike_detector_instance/x4[9]/q spike_detector_instance/x4_reg[9]/Q -type DFF DFF
add mapped point spike_detector_instance/x4[7]/q spike_detector_instance/x4_reg[7]/Q -type DFF DFF
add mapped point spike_detector_instance/x4[12]/q spike_detector_instance/x4_reg[12]/Q -type DFF DFF
add mapped point spike_detector_instance/x4[2]/q spike_detector_instance/x4_reg[2]/Q -type DFF DFF
add mapped point spike_detector_instance/state/q spike_detector_instance/state_reg/Q -type DFF DFF
add mapped point spike_detector_instance/aso[0]/q spike_detector_instance/aso_reg[0]/Q -type DFF DFF
add mapped point spike_detector_instance/aso[1]/q spike_detector_instance/aso_reg[1]/Q -type DFF DFF
add mapped point spike_detector_instance/aso[2]/q spike_detector_instance/aso_reg[2]/Q -type DFF DFF
add mapped point spike_detector_instance/aso[3]/q spike_detector_instance/aso_reg[3]/Q -type DFF DFF
add mapped point spike_detector_instance/aso[4]/q spike_detector_instance/aso_reg[4]/Q -type DFF DFF
add mapped point spike_detector_instance/aso[5]/q spike_detector_instance/aso_reg[5]/Q -type DFF DFF
add mapped point spike_detector_instance/aso[6]/q spike_detector_instance/aso_reg[6]/Q -type DFF DFF
add mapped point spike_detector_instance/aso[7]/q spike_detector_instance/aso_reg[7]/Q -type DFF DFF
add mapped point spike_detector_instance/aso[8]/q spike_detector_instance/aso_reg[8]/Q -type DFF DFF
add mapped point spike_detector_instance/aso[9]/q spike_detector_instance/aso_reg[9]/Q -type DFF DFF
add mapped point spike_detector_instance/aso[10]/q spike_detector_instance/aso_reg[10]/Q -type DFF DFF
add mapped point spike_detector_instance/aso[11]/q spike_detector_instance/aso_reg[11]/Q -type DFF DFF
add mapped point spike_detector_instance/aso[12]/q spike_detector_instance/aso_reg[12]/Q -type DFF DFF
add mapped point spike_detector_instance/aso[13]/q spike_detector_instance/aso_reg[13]/Q -type DFF DFF
add mapped point spike_detector_instance/aso[14]/q spike_detector_instance/aso_reg[14]/Q -type DFF DFF
add mapped point spike_detector_instance/aso[15]/q spike_detector_instance/aso_reg[15]/Q -type DFF DFF
add mapped point spike_detector_instance/spike_detected/q spike_detector_instance/spike_detected_reg/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
